//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleClientApp.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Threading;
    using System.Threading.Tasks;

    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public event EventHandler<EventArgs> OnDbUpdated;

        public override int SaveChanges()
        {
            if (OnDbUpdated != null)
            {
                OnDbUpdated(this, EventArgs.Empty);
            }

            return base.SaveChanges();
        }

        public override Task<int> SaveChangesAsync()
        {
            if (OnDbUpdated != null)
            {
                OnDbUpdated(this, EventArgs.Empty);
            }

            return base.SaveChangesAsync();
        }

        public override Task<int> SaveChangesAsync(CancellationToken cancellationToken)
        {
            if (OnDbUpdated != null)
            {
                OnDbUpdated(this, EventArgs.Empty);
            }

            return base.SaveChangesAsync(cancellationToken);
        }

        public virtual DbSet<Customers> CustomersSet { get; set; }
        public virtual DbSet<Goods> GoodsSet { get; set; }
        public virtual DbSet<Sells> SellsSet { get; set; }
    }
}
