//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleClientApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells
    {
        public int Id { get; set; }
        public int CustomersID { get; set; }
        public int GoodsID { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public decimal Total { get; set; }
    }
}
